#!/bin/sh
#
# This script will be executed *after* all the other init scripts.
# You can put your own initialization stuff in here if you don't
# want to do the full Sys V style init stuff.

touch /var/lock/subsys/local


echo never > /sys/kernel/mm/transparent_hugepage/enabled
echo never > /sys/kernel/mm/transparent_hugepage/defrag
ulimit -H -n 50000
ulimit -S -n 40000
sysctl -w net.core.netdev_max_backlog=4096
sysctl -w net.core.somaxconn=4096
sysctl -w net.ipv4.tcp_max_syn_backlog=4096

###mkfs.xfs -f -i size=512  /dev/sda5
###mount -t xfs -o noatime,nodiratime,attr2,nobarrier,logbufs=8,logbsize=256k,osyncisdsync /dev/sda5 /data

/usr/local/src/iptraf-logger/iptraf-log-to-file.sh

/etc/rc.d/init.d/mysql start
/etc/rc.d/init.d/pdnsd start
/etc/rc.d/init.d/named start
/etc/rc.d/init.d/httpd start
/etc/rc.d/init.d/squid start
/etc/rc.d/init.d/dhcpd start
/usr/local/webadmin/wifidirect/startup-mac-open.sh
/usr/local/webadmin/config/start

