#!/bin/sh
set -e

NAME=ssh

[ "$1" = -1 ] && echo "runsv: ERROR in $NAME: unexpected error or wrong sh syntax"
# no need to stop the service here, runsv will stop trying after the first attempt

[ "$1" = 161 ] && echo "runsv: ERROR $1 in $NAME: disabled by local settings" \
     && sv d "$(dirname "$0")" && exit 0

[ "$1" = 162 ] && echo "runsv: ERROR $1 in $NAME: configtest or early setup failed" \
     && sv d "$(dirname "$0")" && exit 0

echo "$NAME Stopped"   

